### ISSUE TITLE
Fix problem statement in barshelf

### ISSUE THREAD

**Issue by thorehusfeldt** [thorehusfeldt/will-code-for-drinks-F2019#16]
A “4” should be a “2” in the problem description of barshelf, fixed in
3b8685a15b8b15a8e726ec1fc37deedfbc7e3a68 .

This should migrate to open kattis as well.

**Comment by ghamerly** [comment]
Hi, this was fixed a couple of days ago (thanks to a careful-eyed reader that reminded me of the issue); thankfully the problem was already corrected in the repository so it was easy for me to confirm that the update was necessary.
